// Code generated by cmd/gql-sync; DO NOT EDIT.

package twitter

// generatedFeatures is the GraphQL feature-flag default set extracted from
// x.com's bundles (names) and warm-page featureSwitch.defaultConfig (defaults).
// gqlFeatures() returns a copy of this when non-empty, else committedFeatures().
//
// Initial commit = the committedFeatures() baseline verbatim, so the first ship
// is a no-op; cmd/gql-sync overwrites it with the live-extracted defaults.
var generatedFeatures = map[string]any{
	"articles_preview_enabled":                                                true,
	"c9s_tweet_anatomy_moderator_badge_enabled":                               true,
	"communities_web_enable_tweet_community_results_fetch":                    true,
	"content_disclosure_ai_generated_indicator_enabled":                       true,
	"content_disclosure_indicator_enabled":                                    true,
	"creator_subscriptions_tweet_preview_api_enabled":                         true,
	"freedom_of_speech_not_reach_fetch_enabled":                               true,
	"graphql_is_translatable_rweb_tweet_is_translatable_enabled":              true,
	"longform_notetweets_consumption_enabled":                                 true,
	"longform_notetweets_inline_media_enabled":                                true,
	"longform_notetweets_rich_text_read_enabled":                              true,
	"post_ctas_fetch_enabled":                                                 true,
	"premium_content_api_read_enabled":                                        false,
	"profile_label_improvements_pcf_label_in_post_enabled":                    true,
	"responsive_web_edit_tweet_api_enabled":                                   true,
	"responsive_web_enhance_cards_enabled":                                    false,
	"responsive_web_graphql_exclude_directive_enabled":                        true,
	"responsive_web_graphql_skip_user_profile_image_extensions_enabled":       false,
	"responsive_web_graphql_timeline_navigation_enabled":                      true,
	"responsive_web_grok_analysis_button_from_backend":                        true,
	"responsive_web_grok_analyze_button_fetch_trends_enabled":                 true,
	"responsive_web_grok_analyze_post_followups_enabled":                      true,
	"responsive_web_grok_annotations_enabled":                                 true,
	"responsive_web_grok_community_note_auto_translation_is_enabled":          true,
	"responsive_web_grok_image_annotation_enabled":                            true,
	"responsive_web_grok_imagine_annotation_enabled":                          true,
	"responsive_web_grok_share_attachment_enabled":                            true,
	"responsive_web_grok_show_grok_translated_post":                           true,
	"responsive_web_jetfuel_frame":                                            true,
	"responsive_web_profile_redirect_enabled":                                 true,
	"responsive_web_twitter_article_tweet_consumption_enabled":                true,
	"rweb_tipjar_consumption_enabled":                                         true,
	"rweb_video_screen_enabled":                                               true,
	"standardized_nudges_misinfo":                                             true,
	"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,
	"verified_phone_label_enabled":                                            false,
	"view_counts_everywhere_api_enabled":                                      true,
}
