// Code generated by cmd/gql-sync; DO NOT EDIT.

package twitter

// generatedFeatures is the GraphQL feature-flag set: NAMES discovered from
// x.com's bundles ∩ warm-page featureSwitch.defaultConfig, with VALUES taken
// from committedFeatures() for every KNOWN flag (committed values are the
// authed-session authority — the warm page is logged-out and its guest
// defaults legitimately differ). The guest default is shown as a trailing
// comment on every line; a flag NEW to the committed set adopts the guest
// default and is flagged for an authed-capture verification.
// gqlFeatures() returns a copy of this when non-empty, else committedFeatures().
var generatedFeatures = map[string]any{
	"articles_preview_enabled":                                                true,  // warm-page guest default: true
	"c9s_tweet_anatomy_moderator_badge_enabled":                               true,  // warm-page guest default: true
	"communities_web_enable_tweet_community_results_fetch":                    true,  // warm-page guest default: true
	"content_disclosure_ai_generated_indicator_enabled":                       true,  // warm-page guest default: true
	"content_disclosure_indicator_enabled":                                    true,  // warm-page guest default: true
	"creator_subscriptions_tweet_preview_api_enabled":                         true,  // warm-page guest default: true
	"freedom_of_speech_not_reach_fetch_enabled":                               true,  // warm-page guest default: true
	"graphql_is_translatable_rweb_tweet_is_translatable_enabled":              true,  // warm-page guest default: true
	"longform_notetweets_consumption_enabled":                                 true,  // warm-page guest default: true
	"longform_notetweets_inline_media_enabled":                                true,  // warm-page guest default: false
	"longform_notetweets_rich_text_read_enabled":                              true,  // warm-page guest default: true
	"post_ctas_fetch_enabled":                                                 true,  // warm-page guest default: false
	"premium_content_api_read_enabled":                                        false, // warm-page guest default: false
	"profile_label_improvements_pcf_label_in_post_enabled":                    true,  // warm-page guest default: true
	"responsive_web_edit_tweet_api_enabled":                                   true,  // warm-page guest default: true
	"responsive_web_enhance_cards_enabled":                                    false, // warm-page guest default: false
	"responsive_web_graphql_timeline_navigation_enabled":                      true,  // warm-page guest default: true
	"responsive_web_grok_analysis_button_from_backend":                        true,  // warm-page guest default: true
	"responsive_web_grok_analyze_button_fetch_trends_enabled":                 true,  // warm-page guest default: false
	"responsive_web_grok_analyze_post_followups_enabled":                      true,  // warm-page guest default: false
	"responsive_web_grok_annotations_enabled":                                 true,  // warm-page guest default: true
	"responsive_web_grok_community_note_auto_translation_is_enabled":          true,  // warm-page guest default: true
	"responsive_web_grok_image_annotation_enabled":                            true,  // warm-page guest default: true
	"responsive_web_grok_imagine_annotation_enabled":                          true,  // warm-page guest default: true
	"responsive_web_grok_share_attachment_enabled":                            true,  // warm-page guest default: true
	"responsive_web_grok_show_grok_translated_post":                           true,  // warm-page guest default: true
	"responsive_web_jetfuel_frame":                                            true,  // warm-page guest default: true
	"responsive_web_profile_redirect_enabled":                                 true,  // warm-page guest default: true
	"responsive_web_twitter_article_tweet_consumption_enabled":                true,  // warm-page guest default: true
	"rweb_cashtags_composer_attachment_enabled":                               true,  // warm-page guest default: true — NEW — verify against an AUTHED capture before trusting this default
	"rweb_cashtags_enabled":                                                   true,  // warm-page guest default: true — NEW — verify against an AUTHED capture before trusting this default
	"rweb_tipjar_consumption_enabled":                                         true,  // warm-page guest default: false
	"rweb_video_screen_enabled":                                               true,  // warm-page guest default: false
	"spaces_2022_h2_clipping":                                                 true,  // warm-page guest default: true — NEW — verify against an AUTHED capture before trusting this default
	"spaces_2022_h2_spaces_communities":                                       true,  // warm-page guest default: true — NEW — verify against an AUTHED capture before trusting this default
	"standardized_nudges_misinfo":                                             true,  // warm-page guest default: true
	"tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled": true,  // warm-page guest default: true
	"verified_phone_label_enabled":                                            false, // warm-page guest default: false
	"view_counts_everywhere_api_enabled":                                      true,  // warm-page guest default: true
}

// REMOVED — present in the prior baseline but absent from the latest bundle
// extraction. NOT auto-deleted: a flag x.com still requires is an HTTP 400 on
// every call. Review and restore (re-add to committedFeatures) or delete.
//	responsive_web_graphql_exclude_directive_enabled (was true)
//	responsive_web_graphql_skip_user_profile_image_extensions_enabled (was false)
