// Code generated by cmd/gql-sync; DO NOT EDIT.

package twitter

var generatedQueryIDs = map[string]string{
	"CreateTweet":      "7TKRKCPuAGsmYde0CudbVg",
	"Followers":        "9jsVJ9l2uXUIKslHvJqIhw",
	"Following":        "OLm4oHZBfqWx8jbcEhWoFw",
	"Retweeters":       "FeoLYPQ-q4bmjGLTZTGs0g",
	"SearchTimeline":   "GcXk9vN_d1jUfHNqLacXQA",
	"TweetDetail":      "VWFGPVAGkZMGRKGe3GFFnA",
	"UserByRestId":     "VQfQ9wwYdk6j_u2O4vt64Q",
	"UserByScreenName": "IGgvgiOx4QZndDHuD3x9TQ",
	"UserTweets":       "FOlovQsiHGDls3c0Q_HaSQ",
}
