package main

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generatedHeader is the canonical code-generation marker. It MUST match Go's
// `^// Code generated .* DO NOT EDIT\.$` convention so tooling treats the file
// as generated.
const generatedHeader = "// Code generated by cmd/gql-sync; DO NOT EDIT."

// renderQueryIDs emits the gofmt'd source of queryids_gen.go for the given
// operationName -> queryId map. Keys are sorted for a stable diff. The optional
// date stamp is included only when non-empty (callers pass it via -date), so the
// default output is content-only and never churns the diff on an unchanged run.
func renderQueryIDs(ids map[string]string, date string) ([]byte, error) {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	if date != "" {
		b.WriteString("// generated ")
		b.WriteString(date)
		b.WriteString("\n")
	}
	b.WriteString("\npackage twitter\n\nvar generatedQueryIDs = map[string]string{\n")

	names := make([]string, 0, len(ids))
	for name := range ids {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		b.WriteString("\t")
		b.WriteString(strconv.Quote(name))
		b.WriteString(": ")
		b.WriteString(strconv.Quote(ids[name]))
		b.WriteString(",\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}
